version: '3.8'

services:
  github-notion-sync:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: github-notion-sync
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
      - ../logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - nginx-proxy
    networks:
      - sync-network

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx-app.conf:/etc/nginx/conf.d/default.conf:ro
      - ../logs/nginx:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - github-notion-sync
    networks:
      - sync-network

networks:
  sync-network:
    driver: bridge

# Docker Compose 部署命令：
# docker-compose -f deploy/docker-compose.yml up -d
# docker-compose -f deploy/docker-compose.yml ps
# docker-compose -f deploy/docker-compose.yml logs -f github-notion-sync
#
# 验证命令：
# docker-compose -f deploy/docker-compose.yml exec github-notion-sync curl http://localhost:8000/health
# curl -i http://localhost/health
