version: '3.8'

services:
  app:
    image: ${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG:-latest}
    container_name: github-notion-sync-prod
    restart: always
    ports:
      - "${SERVICE_PORT:-8000}:8000"
    environment:
      # 基础配置
      - APP_PORT=8000
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production

      # 数据库配置
      - DB_URL=sqlite:///data/sync.db

      # GitHub 配置
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}

      # Notion 配置 (可选)
      - NOTION_TOKEN=${NOTION_TOKEN:-}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID:-}

      # 安全和限制
      - RATE_LIMIT_PER_MINUTE=60
      - MAX_REQUEST_SIZE=1048576
      - DEADLETTER_REPLAY_TOKEN=${DEADLETTER_REPLAY_TOKEN:-default-token-123}

      # 生产配置
      - DISABLE_NOTION=false
      - DISABLE_METRICS=false

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs

    labels:
      - "com.github-notion-sync.environment=production"
      - "com.github-notion-sync.version=${IMAGE_TAG:-latest}"
      - "com.github-notion-sync.deployment-time=${DEPLOYMENT_TIME:-unknown}"

    networks:
      - github-notion-network

    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

networks:
  github-notion-network:
    driver: bridge
