version: "3.9"

services:
  app:
    ports: []  # 使用反代时，应用不直接暴露端口

  proxy:
    image: caddy:2.7-alpine
    container_name: proxy
    restart: unless-stopped
    depends_on:
      - app
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - EMAIL_FOR_SSL=${EMAIL_FOR_SSL}
    volumes:
      - ./reverse-proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "443:443"

volumes:
  caddy_data:
  caddy_config:
