version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.dev
    image: local/dev-api:latest
    env_file:
      - .env
    environment:
      ENVIRONMENT: development
      LOG_LEVEL: INFO
      APP_PORT: 8000
      DB_URL: postgresql+psycopg2://postgres:postgres@db:5432/app
      GITEE_WEBHOOK_SECRET: ${GITEE_WEBHOOK_SECRET:-dev-secret}
      GITHUB_WEBHOOK_SECRET: ${GITHUB_WEBHOOK_SECRET:-dev-secret}
      DEADLETTER_REPLAY_TOKEN: ${DEADLETTER_REPLAY_TOKEN:-dev-secret}
      REDIS_URL: redis://redis:6379/0
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_BUCKET: ${MINIO_BUCKET:-dev-bucket}
    command: bash -lc "python scripts/init_db.py || true; uvicorn app.server:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - prefect
      - redis
      - minio

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "6379:6379"

    depends_on:
      - minio
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "bash scripts/init_minio.sh && tail -f /dev/null" ]
    volumes:
      - ./:/app

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-dev@local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-devpass}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      - db

  prefect:
    image: prefecthq/prefect:2-latest
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: sqlite+aiosqlite:///root/.prefect/prefect.db
    command: [ "prefect", "orion", "start", "--host", "0.0.0.0" ]
    ports:
      - "4200:4200"

volumes:
  pg_data:
  minio_data:
