name: Setup SSH Access

on:
  workflow_dispatch:

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH Key
      run: |
        # 生成新的 SSH 密钥对
        ssh-keygen -t rsa -b 2048 -f ./temp-key -N ""

        # 显示公钥（需要手动添加到服务器）
        echo "Public Key:"
        cat ./temp-key.pub

        # 将私钥保存为 GitHub Secret
        echo "Private Key (save as GitHub Secret):"
        cat ./temp-key
