version: '1.0'
name: branch-pipeline
displayName: BranchPipeline
stages:
  - stage:
    name: build
    displayName: 分支构建与冒烟
    steps:
      - step: build@python
        name: docker_build_and_smoke
        displayName: Docker 构建 + 冒烟
        pythonVersion: '3.11'
        commands:
          - python3 -V
          - docker build -f Dockerfile -t branch-ci:latest .
          - docker run -d --name branch-app -p 8000:8000 branch-ci:latest
          - sleep 2
          - curl -fsS http://127.0.0.1:8000/health
          - code=$(curl -sS -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/metrics/); if [ "$code" != "200" ]; then docker logs branch-app; exit 1; fi
          - BODY='{"issue":{"id":8001,"number":8001,"title":"gitee-branch-ci"}}'
          - SIG=$(python3 - <<'PY'
import hmac,hashlib
sec=b"ci-secret"; body=b'{"issue":{"id":8001,"number":8001,"title":"gitee-branch-ci"}}'
print(hmac.new(sec, body, hashlib.sha256).hexdigest())
PY
            )
          - curl -fsS -H "X-Gitee-Token: $SIG" -H "X-Gitee-Event: Issue Hook" -H "Content-Type: application/json" -d "$BODY" http://127.0.0.1:8000/gitee_webhook >/dev/null || true
          - docker logs --tail 50 branch-app
          - docker rm -f branch-app
triggers:
  push:
    branches:
      exclude:
        - main
      include:
        - .*
