version: '1.0'
name: pr-pipeline
displayName: PRPipeline
stages:
  - stage:
    name: pr_check
    displayName: PR 构建与冒烟
    steps:
      - step: build@python
        name: docker_build_smoke
        displayName: Docker 构建 + 冒烟
        pythonVersion: '3.11'
        commands:
          - docker build -f Dockerfile -t pr-ci:latest .
          - docker run -d --name pr-app -p 8000:8000 pr-ci:latest
          - sleep 2
          - curl -fsS http://127.0.0.1:8000/health
          - code=$(curl -sS -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/metrics/); if [ "$code" != "200" ]; then docker logs pr-app; exit 1; fi
          - BODY='{"issue":{"id":7001,"number":7001,"title":"gitee-pr-ci"}}'
          - SIG=$(python3 - <<'PY'
import hmac,hashlib
sec=b"ci-secret"; body=b'{"issue":{"id":7001,"number":7001,"title":"gitee-pr-ci"}}'
print(hmac.new(sec, body, hashlib.sha256).hexdigest())
PY
            )
          - curl -fsS -H "X-Gitee-Token: $SIG" -H "X-Gitee-Event: Issue Hook" -H "Content-Type: application/json" -d "$BODY" http://127.0.0.1:8000/gitee_webhook >/dev/null || true
          - docker logs --tail 50 pr-app
          - docker rm -f pr-app
 triggers:
  pr:
    branches:
      include:
        - main
